AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket and IAM user with access to that bucket.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Subscriptor's configuration"
        Parameters:
          - SubscriptorPwd
    ParameterLabels:
      SubscriptorPwd:
        default: "Password for this subscriptor account"

Resources:
  CfdiWareHouse:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub einvoice-${AWS::StackName}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  Subscriptor:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${AWS::StackName}
      LoginProfile:
        Password: !Ref SubscriptorPwd
      Policies:
        - PolicyName: cfdiwarehouse-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${CfdiWareHouse}
                - !Sub arn:aws:s3:::${CfdiWareHouse}/*

Parameters:
  SubscriptorPwd:
    NoEcho: true
    Description: The subscriptor account password
    Type: String
    MinLength: 1
    MaxLength: 41
