name: Sandra CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      e-invoice-dir: "./DOS/e-invoice"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile java code of e-invoice
        working-directory: ${{env.e-invoice-dir}}/service
        run: |
          # Generates all .class stuff
          mvn compile  
      - name: Package and Test the java e-invoice jars
        working-directory: ${{env.e-invoice-dir}}/service
        run: |
          # It implicitly carries out compilation if needed
          mvn package
      - name: Provision DynamoDB
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test_products_dal.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/scripts/test_products_dal.sh"
